datafile=config/validations.xml
cron.expression=0 0/1 * 1/1 * ?

# Mail (SMTP) configuration
spring.mail.host=${SMTP_HOST}
spring.mail.port=587
spring.mail.username=${NOTIF_FROM}
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notifications.from=${NOTIF_FROM}
notifications.to=${NOTIF_TO}
jwt.signing.secret=${JWT_SECRET}
