name: Java CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  MAILER_APIKEY: ''
  NOTIF_FROM: ''
  NOTIF_TO: ''
  JWT_SECRET: ''

# Allow the workflow to publish_branch
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload coverage report to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml
      - name: Move index.html file to root dir
        run: mv target/site/asciidoc/index.html target/site/

      - name: Deploy to GitHub Pages
        if: success() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site
          publish_branch: gh-pages
